title: The Old Star Inn
baseURL: https://theoldstarinn.com
languageCode: en-uk
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
params:
  background_color_class: bg-black
  description: The last theme you'll ever need. Maybe.
  facebook: https://www.facebook.com/pages/Ye-Old-Star-Inn-Bridlington
  favicon: ''
  featured_image: /images/starinn_logo.jpg
  github: ''
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 0
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: https://twitter.com/GoHugoIO
  youtube: ''
